import assert from 'node:assert/strict';
import path from 'node:path';
import { existsSync } from 'node:fs';
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { createFixtures, createLargeFixture, dependency, generated, root } from './fixtures.mjs';
import { createServer } from '../server.mjs';
import { cleanText, pdfDate, commentText } from '../format.js';

assert.equal(cleanText(' x\u0000\ny\r '),'x y');
assert.equal(pdfDate('D:20240229110000+13\'00\''),'2024-02-29');
assert.equal(pdfDate('D:20260230'),'Date invalide');
assert.equal(pdfDate(''),'N/A');
assert.equal(commentText({ type:'StrikeOut',markedText:'removed',note:'' },'en'),'Struck-through text: "removed"');
await createFixtures();
await mkdir(path.join(root,'tests','output'),{ recursive:true });
const { chromium } = dependency('playwright');
const JSZip = dependency('jszip');
const server = createServer();
await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ channel:process.env.TEST_BROWSER || 'chrome', headless:true });
const context = await browser.newContext({ acceptDownloads:true, viewport:{width:1360,height:1050}, locale:'fr-CA' });
const page = await context.newPage();
const errors = [], requests = [];
page.on('pageerror',error => errors.push(error.message));
page.on('request',request => requests.push(request.url()));
const openFile = async name => {
  await page.locator('#file').setInputFiles(path.join(generated,name));
  await page.waitForFunction(() => document.querySelector('#progress-card').hidden,{ timeout:60000 });
};
try {
  await page.goto(base);
  await page.waitForFunction(() => !document.querySelector('#choose').disabled);
  await page.screenshot({ path:path.join(root,'tests','output','start.png'),fullPage:true });
  await openFile('annotations.pdf');
  assert.equal(await page.locator('#count').innerText(),'8');
  assert.equal(await page.locator('#rows tr').count(),8);
  assert.match(await page.locator('#rows').innerText(),/Texte surligné: "Highlighted words" — Keep highlight/);
  assert.match(await page.locator('#rows').innerText(),/Texte barré: "Struck words"/);
  assert.match(await page.locator('#rows').innerText(),/Date invalide/);
  assert.match(await page.locator('#rows').innerText(),/Hidden note retained/);
  assert.equal(await page.locator('#rows img').count(),0);
  assert.equal(await page.evaluate(() => window.pwned),undefined);
  await page.locator('#diagnostics summary').click();
  assert.match(await page.locator('#warning-list').innerText(),/Square \(1\)/);
  assert.match(await page.locator('#warning-list').innerText(),/1 surlignage/);
  await page.locator('#search').fill('Keep highlight');
  assert.equal(await page.locator('#rows tr').count(),1);
  assert.match(await page.locator('#download').innerText(),/8/);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#download').click();
  const download = await downloadPromise;
  const excelPath = path.join(root,'tests','output','extracted.xlsx');
  await download.saveAs(excelPath);
  const zip = await JSZip.loadAsync(await readFile(excelPath));
  const sheet = await zip.file('xl/worksheets/sheet1.xml').async('string');
  const strings = await zip.file('xl/sharedStrings.xml').async('string');
  assert.match(sheet,/<c r="D3"[^>]*><v>8<\/v>/);
  assert.match(sheet,/<row r="15"/);
  assert.match(sheet,/ySplit="7"/);
  assert.match(strings,/Commentaire/);
  assert.match(strings,/Highlighted words/);
  assert.match(strings,/&lt;img/);
  assert.match(strings,/=1\+1/);
  assert.doesNotMatch(sheet,/<f[ >]/);
  assert.doesNotMatch(strings,/Atkins|ATRL|atkinsrealis/i);
  await page.locator('#reset-filters').click();
  await page.locator('#language').selectOption('en');
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.match(await page.locator('#rows').innerText(),/Highlighted text/);
  await page.locator('#type-filter').selectOption('Text');
  assert.equal(await page.locator('#rows tr').count(),4);
  await page.locator('#reset-filters').click();
  await page.locator('#language').selectOption('fr');
  await page.screenshot({ path:path.join(root,'tests','output','comments.png'),fullPage:true });
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({ path:path.join(root,'tests','output','mobile.png'),fullPage:true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth),false);
  await page.setViewportSize({width:1360,height:1050});
  await page.locator('#clear').click();
  assert.equal(await page.locator('#rows tr').count(),0);
  assert.equal(await page.locator('#results').isVisible(),false);
  await openFile('empty.pdf');
  assert.match(await page.locator('#status').innerText(),/Aucun commentaire/);
  assert.equal(await page.locator('#download').isDisabled(),true);
  await openFile('invalid.pdf');
  assert.match(await page.locator('#status').innerText(),/PDF valide/);
  await openFile('corrupt.pdf');
  assert.match(await page.locator('#status').innerText(),/corrompu/);
  await openFile('long.pdf');
  await page.locator('#download').click();
  assert.match(await page.locator('#status').innerText(),/32 767/);
  // Inject PDF.js failures to verify both partial-result paths deterministically.
  // A damaged PDF can be silently repaired by PDF.js instead of raising an error.
  await page.evaluate(async () => {
    const pdfjs = await import('./vendor/pdfjs/pdf.mjs');
    const document = await pdfjs.getDocument({data:new Uint8Array(await (await fetch('./example.pdf')).arrayBuffer())}).promise;
    const prototype = Object.getPrototypeOf(await document.getPage(1));
    const text = prototype.getTextContent, annotations = prototype.getAnnotations;
    prototype.getTextContent = function(options) { return this.pageNumber === 2 ? Promise.reject(new Error('Simulated text failure')) : text.call(this,options); };
    prototype.getAnnotations = function(options) { return this.pageNumber === 3 ? Promise.reject(new Error('Simulated page failure')) : annotations.call(this,options); };
    window.restorePdfMethods = () => { prototype.getTextContent = text; prototype.getAnnotations = annotations; };
    await document.destroy();
  });
  await openFile('partial.pdf');
  assert.match(await page.locator('#status').innerText(),/partielle/);
  assert.equal(await page.locator('#count').innerText(),'2');
  assert.equal(await page.locator('#download').isDisabled(),true);
  await page.locator('#accept-partial').check();
  const partialDownloadPromise = page.waitForEvent('download');
  await page.locator('#download').click();
  const partialDownload = await partialDownloadPromise;
  const partialPath = path.join(root,'tests','output','partial.xlsx');
  await partialDownload.saveAs(partialPath);
  const partialZip = await JSZip.loadAsync(await readFile(partialPath));
  assert.match(await partialZip.file('xl/sharedStrings.xml').async('string'),/Extraction partielle/);
  await page.evaluate(() => { window.restorePdfMethods(); delete window.restorePdfMethods; });
  await page.locator('#clear').click();
  await page.locator('#demo').click();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '5' && document.querySelector('#progress-card').hidden);
  assert.equal(await page.locator('#rows tr').count(),5);
  await page.screenshot({path:path.join(root,'tests','output','demo.png'),fullPage:true});
  // Verify cancellation while sequential extraction is active.
  await page.locator('#file').setInputFiles(path.join(generated,'pages.pdf'));
  await page.waitForFunction(() => !document.querySelector('#progress-card').hidden);
  await page.locator('#cancel').click();
  await page.waitForFunction(() => document.querySelector('#progress-card').hidden);
  assert.match(await page.locator('#status').innerText(),/annulée/);
  assert.equal(await page.locator('#results').isVisible(),false);
  await openFile('pages.pdf');
  assert.equal(await page.locator('#count').innerText(),'500');
  assert.equal(await page.locator('#rows tr').count(),50);
  await page.locator('#next').click();
  assert.equal(await page.locator('#rows tr:first-child td:first-child').innerText(),'51');
  await page.locator('#page-filter').selectOption('500');
  assert.equal(await page.locator('#rows tr').count(),1);
  assert.match(await page.locator('#rows').innerText(),/Page 500/);

  // Exercise the real local example without publishing or modifying it.
  const source = path.join(root,'..','Exemples et modèles','Template commentaires possibles.pdf');
  let sourceCount = null;
  if (existsSync(source)) {
    await page.locator('#file').setInputFiles(source);
    await page.waitForFunction(() => document.querySelector('#progress-card').hidden,{timeout:60000});
    sourceCount = Number(await page.locator('#count').innerText());
    assert.ok(sourceCount > 0,'Local reference PDF should have retained annotations');
    console.log(`Local reference PDF: ${sourceCount} retained annotations`);
  } else console.log('Local historical reference PDF not present; synthetic checks still apply.');

  let stress = null;
  if (process.argv.includes('--stress')) {
    createLargeFixture();
    const started = Date.now();
    await openFile('large-300mb.pdf');
    assert.equal(await page.locator('#count').innerText(),'500');
    assert.equal(await page.locator('#pages').innerText(),'500');
    assert.match(await page.locator('#status').innerText(),/terminée/);
    stress = { sizeBytes:(await stat(path.join(generated,'large-300mb.pdf'))).size,pages:500,comments:500,wallSeconds:(Date.now()-started)/1000 };
    console.log(`Synthetic 300 MB stress: ${JSON.stringify(stress)}`);
  }
  assert.deepEqual(errors,[]);
  assert.ok(requests.every(url => url.startsWith(base) || url.startsWith('blob:') || url.startsWith('data:')),'No external requests');
  const summary = {date:new Date().toISOString(),browser:await browser.version(),checks:'annotations, text geometry, literal HTML/formulas, Excel contents, full export with filters, FR/EN, mobile overflow, empty/corrupt files, long-cell block, partial extraction acknowledgement and Excel warning, demo, cancellation, 500 pages, local reference PDF, local-only requests',sourceCount,stress};
  await writeFile(path.join(root,'tests','output','validation.json'),JSON.stringify(summary,null,2));
  await writeFile(path.join(root,'tests','output',`validation-${process.env.TEST_BROWSER || 'chrome'}.json`),JSON.stringify(summary,null,2));
  console.log('PASS: browser extraction, interface, Excel and local-only processing');
} finally { await context.close(); await browser.close(); await new Promise(resolve => server.close(resolve)); }
